version: '3'

services:
   mysql:
    image: mysql:8.0
    container_name: "mysql"
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - devops

networks:
  devops:
    driver: "bridge"